$content = @"
server.port=8081
spring.data.mongodb.uri=mongodb+srv://poddarnidhi0155_db_user:nidhi123@cluster0.4tjdig6.mongodb.net/?appName=Cluster0
logging.level.com.studyplanner=DEBUG
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.default-property-inclusion=non_null
app.cors.allowed-origins=http://localhost:3000
"@
Set-Content -Path "src\main\resources\application.properties" -Value $content